openapi: 3.0.0
info:
  title: Star Wars API - Starships
  version: 1.0.0
servers:
  - url: https://swapi.dev/api
paths:
  /starships:
    get:
      summary: Get list of starships
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 36
                  next:
                    type: string
                    nullable: true
                    example: 'https://swapi.dev/api/starships/?page=2'
                  previous:
                    type: string
                    nullable: true
                    example: 'https://swapi.dev/api/starships/?page=1'
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: 'CR90 corvette'
                        model:
                          type: string
                          example: 'CR90 corvette'
                        manufacturer:
                          type: string
                          example: 'Corellian Engineering Corporation'
                        cost_in_credits:
                          type: string
                          example: '3500000'
                        length:
                          type: string
                          example: '150'
                        max_atmosphering_speed:
                          type: string
                          example: '950'
                        crew:
                          type: string
                          example: '30-165'
                        passengers:
                          type: string
                          example: '600'
                        cargo_capacity:
                          type: string
                          example: '3000000'
                        consumables:
                          type: string
                          example: '1 year'
                        hyperdrive_rating:
                          type: string
                          example: '2.0'
                        MGLT:
                          type: string
                          example: '60'
                        starship_class:
                          type: string
                          example: 'corvette'
                        pilots:
                          type: array
                          items:
                            type: string
                        films:
                          type: array
                          items:
                            type: string
                            example: 'https://swapi.dev/api/films/1/'
                        created:
                          type: string
                          format: date-time
                          example: '2014-12-10T14:20:33.369000Z'
                        edited:
                          type: string
                          format: date-time
                          example: '2014-12-20T21:23:49.867000Z'
                        url:
                          type: string
                          example: 'https://swapi.dev/api/starships/2/'
